In [1]:
#데이터생성

import pandas as pd
import numpy as np
data = pd.DataFrame({
    '메뉴': ['[인기]아이펠치킨','닭강정','간장치킨','마늘치킨','파닭','승일양념치킨','양념반후라이드반','황금후라이드','[베스트]풀잎치킨'],
    '가격': [16000,15000,14000,14000,14000,13000,13000,12000,9900],
    '호수' : [11,12,9,9,11,10,10,10,10],
    '칼로리' : [1200.0,1500.0,1600.0,1800.0,1300.0,1400.0,1300.0,1000.0,1000.0],
    '할인율' : [0.5,0.2,0.2,0.2,0.2,0.2,0.2,0.2,np.nan],
    '할인가' : [8000.0,12000.0,11200.0,11200.0,11200.0,10400.0,10400.0,9600.0,np.nan],
    '원산지' : ['국내산','브라질','국내산','국내산','브라질','국내산','국내산','국내산','국내산'],
    '살찔까요' : ['no','yes','yes','yes','yes','yes','yes','no','no'],
    '고민' : ['무조건먹자','먹지말자','먹지말자','먹지말자','먹지말자','먹지말자','먹지말자','무조건먹자','무조건먹자']
})
data.to_csv('~/aiffel/fund/final_modudak.csv', index=False)
data

메뉴     가격  호수     칼로리  할인율      할인가  원산지 살찔까요     고민
0  [인기]아이펠치킨  16000  11  1200.0  0.5   8000.0  국내산   no  무조건먹자
1        닭강정  15000  12  1500.0  0.2  12000.0  브라질  yes   먹지말자
2       간장치킨  14000   9  1600.0  0.2  11200.0  국내산  yes   먹지말자
3       마늘치킨  14000   9  1800.0  0.2  11200.0  국내산  yes   먹지말자
4         파닭  14000  11  1300.0  0.2  11200.0  브라질  yes   먹지말자
5     승일양념치킨  13000  10  1400.0  0.2  10400.0  국내산  yes   먹지말자
6   양념반후라이드반  13000  10  1300.0  0.2  10400.0  국내산  yes   먹지말자
7     황금후라이드  12000  10  1000.0  0.2   9600.0  국내산   no  무조건먹자
8  [베스트]풀잎치킨   9900  10  1000.0  NaN      NaN  국내산   no  무조건먹자

In [2]:
# 데이터 변경
data.loc[2,'원산지'] = '미국' #로케이션 지정해주기.

data.head()


메뉴     가격  호수     칼로리  할인율      할인가  원산지 살찔까요     고민
0  [인기]아이펠치킨  16000  11  1200.0  0.5   8000.0  국내산   no  무조건먹자
1        닭강정  15000  12  1500.0  0.2  12000.0  브라질  yes   먹지말자
2       간장치킨  14000   9  1600.0  0.2  11200.0   미국  yes   먹지말자
3       마늘치킨  14000   9  1800.0  0.2  11200.0  국내산  yes   먹지말자
4         파닭  14000  11  1300.0  0.2  11200.0  브라질  yes   먹지말자

In [3]:
# 활용할 데이터 선택. 필요한 컬럼만 가져오기.
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
#(data의 칼럼 리스트 주면 그 리스트에 따라 ----이터러블)
df
df.head()

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() # 사이킷런은 프레임워크다 프레임워크다.
le.fit(df['원산지'])
type(le.fit(df['원산지']))

a= le.transform(df['원산지'])
type(a)

numpy.ndarray

레이블인코더로 컬럼을 레이블링 (숫자로 표시됨)하고  
그 결과를 a로 가져온다.
a는 ndarray 타입으로 반환됨.

fit_transform(y)
Fit label encoder and return encoded labels.
즉 레이블인코딩과, 인코딩된 라벨 값을 반환하는 작업을 동시에 함

*동시에 하지 않는 경우가 궁금하다.

In [5]:
a

array([0, 2, 1, 0, 2, 0, 0, 0, 0])

In [6]:
df['살찔까요'] = le.fit_transform(df['살찔까요'])
df

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0  국내산     0
1  15000  12  1500.0  브라질     1
2  14000   9  1600.0   미국     1
3  14000   9  1800.0  국내산     1
4  14000  11  1300.0  브라질     1
5  13000  10  1400.0  국내산     1
6  13000  10  1300.0  국내산     1
7  12000  10  1000.0  국내산     0
8   9900  10  1000.0  국내산     0

In [7]:
# 데이터가 object 타입인 column 선택 ['원산지', '살찔까요']

# 방법1 
# cols = ['원산지', '살찔까요']

# 방법2
cols = df.select_dtypes(include='object').columns
cols

Index(['원산지'], dtype='object')

In [8]:
# 한 번에 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

for col in cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

자료형에 담긴 자료들을 하나씩 꺼내고 싶을때 사용한다.
이렇게 반복문을 활용해서 실행을 하게 되면 컬럼이 아무리 많아도 반복문을 통해서 한번에 인코딩 할 수 있다.


## 원-핫 인코딩
각 카테고리별로 컬럼을 만들어 해당되는 곳은 1, 나머지는 0으로 인코딩  
-> 다중 카테고리 표현 가능 (스릴러장르기도 하면서 판타지이기도 함 같이.)  
각 카테고리들이 서열 없이 평등할 때 쓰기 적합.  
(예를 들어 레이블 인코딩으로 남자1, 여자 2로 레이블링이 될 때 인공지능이 여자를 서열이 높은, 혹은 값이 높은 카테고리로 학습할 가능성이 있음)

In [9]:
# 원핫인코딩
# 데이터프레임을 입력받기 때문에 대괄호를 2번 써야 합니다. (df[['원산지']])

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
cat = ohe.fit_transform(df[['원산지']])
cat

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [10]:
ohe.categories_

[array([0, 1, 2])]

In [11]:
ohe.get_feature_names_out()

array(['원산지_0', '원산지_1', '원산지_2'], dtype=object)

In [12]:
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat

원산지_0  원산지_1  원산지_2
0    1.0    0.0    0.0
1    0.0    0.0    1.0
2    0.0    1.0    0.0
3    1.0    0.0    0.0
4    0.0    0.0    1.0
5    1.0    0.0    0.0
6    1.0    0.0    0.0
7    1.0    0.0    0.0
8    1.0    0.0    0.0

In [13]:
df = pd.concat([df,df_cat],axis=1)
df

가격  호수     칼로리  원산지  살찔까요  원산지_0  원산지_1  원산지_2
0  16000  11  1200.0    0     0    1.0    0.0    0.0
1  15000  12  1500.0    2     1    0.0    0.0    1.0
2  14000   9  1600.0    1     1    0.0    1.0    0.0
3  14000   9  1800.0    0     1    1.0    0.0    0.0
4  14000  11  1300.0    2     1    0.0    0.0    1.0
5  13000  10  1400.0    0     1    1.0    0.0    0.0
6  13000  10  1300.0    0     1    1.0    0.0    0.0
7  12000  10  1000.0    0     0    1.0    0.0    0.0
8   9900  10  1000.0    0     0    1.0    0.0    0.0

In [14]:
# 기존 컬럼 삭제
df = df.drop(['원산지'], axis=1)
df

가격  호수     칼로리  살찔까요  원산지_0  원산지_1  원산지_2
0  16000  11  1200.0     0    1.0    0.0    0.0
1  15000  12  1500.0     1    0.0    0.0    1.0
2  14000   9  1600.0     1    0.0    1.0    0.0
3  14000   9  1800.0     1    1.0    0.0    0.0
4  14000  11  1300.0     1    0.0    0.0    1.0
5  13000  10  1400.0     1    1.0    0.0    0.0
6  13000  10  1300.0     1    1.0    0.0    0.0
7  12000  10  1000.0     0    1.0    0.0    0.0
8   9900  10  1000.0     0    1.0    0.0    0.0

### 여러 개의 컬럼을 한번에 인코딩하기

In [15]:
# 활용할 데이터 선택
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [16]:
# 원핫인코딩
cols = df.select_dtypes(include='object').columns #문자열 타입이 하나라도 있는 컬럼을 선택
ohe = OneHotEncoder(sparse=False)
cat = ohe.fit_transform(df[cols])
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat

원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0      1.0     0.0      0.0      1.0       0.0
1      0.0     0.0      1.0      0.0       1.0
2      0.0     1.0      0.0      0.0       1.0
3      1.0     0.0      0.0      0.0       1.0
4      0.0     0.0      1.0      0.0       1.0
5      1.0     0.0      0.0      0.0       1.0
6      1.0     0.0      0.0      0.0       1.0
7      1.0     0.0      0.0      1.0       0.0
8      1.0     0.0      0.0      1.0       0.0

In [17]:
# 데이터프레임 합치기
df = pd.concat([df, df_cat], axis=1)
df.head()

# 컬럼 삭제
df = df.drop(cols, axis=1)
df



가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0      1.0     0.0      0.0      1.0       0.0
1  15000  12  1500.0      0.0     0.0      1.0      0.0       1.0
2  14000   9  1600.0      0.0     1.0      0.0      0.0       1.0
3  14000   9  1800.0      1.0     0.0      0.0      0.0       1.0
4  14000  11  1300.0      0.0     0.0      1.0      0.0       1.0
5  13000  10  1400.0      1.0     0.0      0.0      0.0       1.0
6  13000  10  1300.0      1.0     0.0      0.0      0.0       1.0
7  12000  10  1000.0      1.0     0.0      0.0      1.0       0.0
8   9900  10  1000.0      1.0     0.0      0.0      1.0       0.0

### 판다스를 이용한 원핫인코딩

In [18]:
# 활용할 데이터 선택
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df.head()

# 판다스를 활용한 원핫 인코딩
df = pd.get_dummies(df)
df

가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0        1       0        0        1         0
1  15000  12  1500.0        0       0        1        0         1
2  14000   9  1600.0        0       1        0        0         1
3  14000   9  1800.0        1       0        0        0         1
4  14000  11  1300.0        0       0        1        0         1
5  13000  10  1400.0        1       0        0        0         1
6  13000  10  1300.0        1       0        0        0         1
7  12000  10  1000.0        1       0        0        1         0
8   9900  10  1000.0        1       0        0        1         0

### 표준화 (StandardScaler)

모든값을 평균이 0, 분산이 1인 표준정규분포로 변환
$z = \frac{x-\mu}{\sigma}$


In [19]:
# StandardScaler(표준화)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(df[['가격']])

# StandardScaler 여러 변수에 적용
cols = ['가격', '호수', '칼로리']
scaler = StandardScaler()
df[cols] = scaler.fit_transform(df[cols])
df

가격        호수       칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  1.542470  0.848875 -0.577920        1       0        0        1         0
1  0.941508  1.940285  0.622376        0       0        1        0         1
2  0.340545 -1.333946  1.022475        0       1        0        0         1
3  0.340545 -1.333946  1.822672        1       0        0        0         1
4  0.340545  0.848875 -0.177822        0       0        1        0         1
5 -0.260417 -0.242536  0.222277        1       0        0        0         1
6 -0.260417 -0.242536 -0.177822        1       0        0        0         1
7 -0.861379 -0.242536 -1.378118        1       0        0        1         0
8 -2.123400 -0.242536 -1.378118        1       0        0        1         0

### 정규화 (MinMaxScaler)

모든 값을 0~1 사이 값으로 변환 (데이터 사이즈 축소)
$x_{scale} = \frac{x-x_{min}}{x_{max}-x_{min}}$  
  
즉 최소값을 0으로 하고 최댓값을 1으로 하는 스케일로 변경

In [20]:
# MinMaxScaler(정규화)
from sklearn.preprocessing import MinMaxScaler
cols = ['가격', '호수', '칼로리']
scaler = MinMaxScaler()
df[cols] = scaler.fit_transform(df[cols])
df
df.describe()

가격        호수       칼로리   원산지_국내산    원산지_미국   원산지_브라질   살찔까요_no  \
count  9.000000  9.000000  9.000000  9.000000  9.000000  9.000000  9.000000   
mean   0.579235  0.407407  0.430556  0.666667  0.111111  0.222222  0.333333   
std    0.289334  0.323942  0.331374  0.500000  0.333333  0.440959  0.500000   
min    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
25%    0.508197  0.333333  0.250000  0.000000  0.000000  0.000000  0.000000   
50%    0.672131  0.333333  0.375000  1.000000  0.000000  0.000000  0.000000   
75%    0.672131  0.666667  0.625000  1.000000  0.000000  0.000000  1.000000   
max    1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

       살찔까요_yes  
count  9.000000  
mean   0.666667  
std    0.500000  
min    0.000000  
25%    0.000000  
50%    1.000000  
75%    1.000000  
max    1.000000

## 사이킷런 데이터 불러오기

In [21]:
# 사이킷런 데이터 불러오기
from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer()
type(dataset)

sklearn.utils.Bunch

In [22]:
# 피처 이름 확인
dataset.feature_names #즉 쉽게 얘기하면 이 데이터에서는 열의 이름

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [23]:
# 타겟 확인
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [24]:
# 데이터 확인
dataset.data[:2]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02]])

In [25]:
# 데이터프레임으로 만들기
cancer_df = pd.DataFrame(data=dataset.data , columns=dataset.feature_names)
cancer_df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [26]:
# 타겟 추가하기
cancer_df['target'] = dataset.target
cancer_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [27]:
# 당뇨병 데이터 불러오기
from sklearn.datasets import load_diabetes
dataset = load_diabetes()
#사이킷런에는 수많은 데이터셋이 있다. 활용가능. 


-------------------------------------------------------------------------------

# 지도학습

## 의사결정나무 모델
지도학습 알고리즘 (분류, 회귀)  
직관적인 알고리즘 (이해 쉬움)  
과대적합되기 쉬운 알고리즘 (트리 깊이 제한 필요)  

In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [29]:
# 데이터 생성
from sklearn.datasets import load_breast_cancer

def make_dataset():
    iris = load_breast_cancer()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['target'] = iris.target
    X_train, X_test, y_train, y_test = train_test_split(
        df.drop('target', axis=1), df['target'], test_size=0.5, random_state=1004)
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = make_dataset()
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((284, 30), (285, 30), (284,), (285,))

In [30]:
# 타겟 확인
y_train.value_counts()

1    190
0     94
Name: target, dtype: int64

#### 의사결정나무
지도학습(분류)에서 가장 유용하게 사용되고 있는 기법 중 하나입니다.  
트리의 루트(root)에서 시작해서 정보이득이 최대가 되는 특성으로 데이터를 나눕니다.  
정보이득(information gain)이 최대가 되는 특성을 나누는 기준(불순도를 측정하는 기준)은 '지니'와 '엔트로피'가 사용됩니다.  
데이터가 한 종류만 있다면 엔트로피/지니 불순도는 0에 가깝고, 서로 다른 데이터의 비율이 비슷하면 1에 가깝습니다.
정보이득(information gain)이 최대라는 것은 불순도를 최소화 하는 방향입니다. (1-불순도)


In [31]:
# 의사결정나무
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=0)
model.fit(X_train, y_train)
pred = model.predict(X_test)
accuracy_score(y_test, pred)


0.9263157894736842

#### 하이퍼파라미터?  
우리가 조정할 수 있는 파라미터값  
criterion (기본값 gini) : 불순도 지표 (또는 엔트로피 불순도 entropy)  
max_depth (기본값 None) : 최대 한도 깊이(적절히 조절 중요!)  
min_samples_split (기본값 2) : 자식 노드를 갖기 위한 최소한의 데이터 수  
min_samples_leaf (기본값 1) : 리프 노드가 되기 위한 최소 샘플 수  

In [32]:
# 의사결정나무 하이퍼파라미터
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(
    criterion = 'entropy', 
    max_depth = 7, 
    min_samples_split = 2,
    min_samples_leaf=2, 
    random_state=0)
model.fit(X_train, y_train)
pred = model.predict(X_test)
accuracy_score(y_test, pred)

0.9228070175438596

Criterion 은 기준, 불순도 지표를 의미하며 기본값은gini이다.  


## 랜덤포레스트  
의사결정 나무가 여러 개 있는 것을 랜덤포레스트 (의사결정트리의앙상블) 
앙상블 방법 : 배깅/ 부스팅 . 랜덤포레스트는 배깅 방법  
여러개의 의사결정 트리로 구성  
앙상블 방법 중 배깅(bagging) 방식  
부트스트랩 샘플링 (데이터셋 중복 허용)  
최종 다수결 투표  
과대적합 가능성 낮음  


In [33]:
# 랜덤포레스트
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state=0)
model.fit(X_train, y_train)
pred = model.predict(X_test)
accuracy_score(y_test, pred)

0.9438596491228071

**랜덤포레스트 하이퍼파라미터**  

n_estimators (기본값 100) : 트리의 수  
criterion (기본값 gini) : 불순도 지표  
max_depth (기본값 None) : 최대 한도 깊이  
min_samples_split (기본값 2) : 자식 노드를 갖기 위한 최소한의 데이터 수  
min_samples_leaf (기본값 1) : 리프 노드가 되기 위한 최소 샘플 수

In [34]:
# 랜덤포레스트 하이퍼파라미터
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=500, max_depth=5, random_state=0)
model.fit(X_train, y_train)
pred = model.predict(X_test)
accuracy_score(y_test, pred)

0.9473684210526315

#### XGboost 모델  
부스팅(앙상블) 기반의 알고리즘  
캐글 대회에서 뛰어난 성능을 보여 인기 굿  

In [35]:
# xgboost
from xgboost import XGBClassifier
model = XGBClassifier(random_state=0, use_label_encoder=False, eval_metric='logloss')
model.fit(X_train, y_train)
pred = model.predict(X_test)
accuracy_score(y_test, pred)

/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 0.996-ko-0.9.2 is an invalid version and will not be supported in a future release
  warnings.warn(


0.9508771929824561

트리 앙상블 중 성능이 좋은 알고리즘  
eXtreme Gradient Boosting를 줄여서 XGBoost라고 한다.  
약한 학습기가 계속해서 업데이트를 하며 좋은 모델을 만들어 간다.  
부스팅(앙상블) 기반의 알고리즘  
캐글(글로벌 AI 경진대회)에서 뛰어난 성능을 보이면서 인기가 높아짐  
  
booster (기본값 gbtree) : 부스팅 알고리즘 (또는 dart, gblinear)  
objective (기본값 binary:logistic) : 이진분류 (다중분류: multi:softmax)  
max_depth (기본값 6) : 최대 한도 깊이  
learning_rate (기본값 0.1) : 학습률  
n_estimators (기본값 100) : 트리의 수  
subsample (기본값 1) : 훈련 샘플 개수의 비율  
colsample_bytree (기본값 1) : 특성 개수의 비율  
n_jobs (기본값 1) : 사용 코어 수 (-1: 모든 코어를 다 사용)  

In [36]:
# xgboost 하이퍼파라미터
model = XGBClassifier(random_state=0, use_label_encoder=False, eval_metric='logloss',
                      booster = 'gbtree',
                      objective = 'binary:logistic',
                      max_depth = 5,
                      learning_rate = 0.05,
                      n_estimators = 500,
                      subsample = 1, 
                      colsample_bytree = 1,
                      n_jobs = -1
                      
                      
# - booster(기본값 gbtree): 부스팅 알고리즘 (또는 dart, gblinear)
# - objective(기본값 binary:logistic): 이진분류 (다중분류: multi:softmax)
# - max_depth(기본값 6): 최대 한도 깊이
# - learning_rate(기본값 0.1): 학습률 (기울기가 0인 지점을 찾을 때, 간격?)
# - n_estimators(기본값 100): 트리의 수
# - subsample(기본값 1): 훈련 샘플 개수의 비율
# - colsample_bytree(기본값 1): 특성 개수의 비율
# - n_jobs(기본값 1): 사용 코어 수 (-1: 모든 코어를 다 사용)
                     )
model.fit(X_train, y_train)
pred = model.predict(X_test)
accuracy_score(y_test, pred)

0.9649122807017544

In [37]:
# 조기종료
model = XGBClassifier(random_state=0, use_label_encoder=False, eval_metric='logloss', 
                     learning_rate = 0.05,
                      n_estimators = 500)
eval_set = [(X_test, y_test)]
model.fit(X_train, y_train, eval_set=eval_set, early_stopping_rounds=10) #검증할 데이터값도 같이 넣어줌.
pred = model.predict(X_test)
accuracy_score(y_test, pred)

[0]	validation_0-logloss:0.65391
[1]	validation_0-logloss:0.61861
[2]	validation_0-logloss:0.58697
[3]	validation_0-logloss:0.55756
[4]	validation_0-logloss:0.53038
[5]	validation_0-logloss:0.50611
[6]	validation_0-logloss:0.48363
[7]	validation_0-logloss:0.46304
[8]	validation_0-logloss:0.44332
[9]	validation_0-logloss:0.42512
[10]	validation_0-logloss:0.40821
[11]	validation_0-logloss:0.39260
[12]	validation_0-logloss:0.37838
[13]	validation_0-logloss:0.36512
[14]	validation_0-logloss:0.35276
[15]	validation_0-logloss:0.34090
[16]	validation_0-logloss:0.33018
[17]	validation_0-logloss:0.31967
[18]	validation_0-logloss:0.30998
[19]	validation_0-logloss:0.30105
[20]	validation_0-logloss:0.29259
[21]	validation_0-logloss:0.28478
[22]	validation_0-logloss:0.27725
[23]	validation_0-logloss:0.27027
[24]	validation_0-logloss:0.26359
[25]	validation_0-logloss:0.25755
[26]	validation_0-logloss:0.25139
[27]	validation_0-logloss:0.24593
[28]	validation_0-logloss:0.24103
[29]	validation_0-loglos

0.9473684210526315

learning_rate(기본값 0.1): 학습률 (기울기가 0인 지점을 찾을 때, 간격?)  
n_estimators(기본값 100)  
두가지는 같이 올려주어야 한다. (간격과 총 트리수를 생각해보자)

### 교차검증


데이터셋을 n개로 쪼개면,(KFold 설정 n)
1~n 번째 데이터셋을 각각 검증 데이터로 쓰며  
n번 검증과 수정을 함.  


In [38]:
# 데이터셋 로드
def make_dataset2():
    iris = load_breast_cancer()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['target'] = iris.target
    return df.drop('target', axis=1), df['target']
X, y = make_dataset2()

In [39]:
# KFold
from sklearn.model_selection import KFold
model = DecisionTreeClassifier(random_state=0)

kfold = KFold(n_splits=5)
for train_idx, test_idx in kfold.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    print(accuracy_score(y_test, pred))

0.8771929824561403
0.9122807017543859
0.9473684210526315
0.9385964912280702
0.8407079646017699


**StratifiedKfold**  

불균형한 타겟 비율을 가진 데이터가 한쪽으로 치우치는 것을 방지

In [40]:
# Stratified Kfold
from sklearn.model_selection import StratifiedKFold
model = DecisionTreeClassifier(random_state=0)

kfold = StratifiedKFold(n_splits=5)
for train_idx, test_idx in kfold.split(X, y):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    print(accuracy_score(y_test, pred))

0.9035087719298246
0.9210526315789473
0.9122807017543859
0.9473684210526315
0.9026548672566371


**사이킷런 교차검증**  
사이킷런 내부 API를 통해 fit(학습) - predict(예측) - evaluation(평가)

In [41]:
# 교차검증
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, X, y, cv=3)
scores

array([0.88947368, 0.94210526, 0.86243386])

In [42]:
# 평균 점수
scores.mean()

0.8980042699340944

In [43]:
# 교차검증 Stratified Kfold
kfold = StratifiedKFold(n_splits=5)
scores = cross_val_score(model, X, y, cv=kfold)
scores

array([0.90350877, 0.92105263, 0.9122807 , 0.94736842, 0.90265487])

In [44]:
# 평균 점수
scores.mean()

0.9173730787144851

### 평가 (분류 모델)
정확도 accuracy: 실제 값과 예측값이 일치하는 비율  
정밀도 precision: 양성이라고 예측한 값 중 실제 양성인 값의 비율 (암이라고 예측 한 값 중 실제 암)  
재현율 recall: 실제 양성 값 중 양성으로 예측한 값의 비율 (암을 암이라고 판단)  
F1: 정밀도와 재현율의 조화평균  
**ROC-AUC**  
ROC: 참 양성 비율(True Positive Rate)에 대한 거짓 양성 비율(False Positive Rate) 곡선  
AUC: ROC곡선 면적 아래 (완벽하게 분류되면 AUC가 1임)




In [45]:
# 정확도
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9026548672566371

In [46]:
# 정밀도
from sklearn.metrics import precision_score
precision_score(y_test, pred)

0.9545454545454546

In [47]:
# 재현율
from sklearn.metrics import recall_score
recall_score(y_test, pred)

0.8873239436619719

In [48]:
# f1
from sklearn.metrics import f1_score
f1_score(y_test, pred)

0.9197080291970803

In [49]:
# roc_auc
from sklearn.metrics import roc_auc_score
model = XGBClassifier(random_state=0, use_label_encoder=False, eval_metric='logloss')
model.fit(X_train, y_train)
pred = model.predict_proba(X_test)
roc_auc_score(y_test, pred[:,1])

0.999664654594232

**정확도, 정밀도, 재현율, F1, ROC-AUC**